image: ubuntu:22.04

stages:
  - build
  - deploy
  
variables:
  GO_VERSION: "1.25.0"
  CGO_ENABLED: "0"
  GOOS: linux
  GOARCH: amd64
  APP_NAME: gocars-api
  APP_DIR: "/home/api"
  SERVICE_NAME: gocars-api   # systemd service name

before_script:
  - apt-get update
  - apt-get install -y wget ca-certificates openssh-client
  - wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go version
  - go mod download

build:
  stage: build
  tags: ["shell"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - go build -o $APP_NAME
  artifacts:
    paths:
      - $APP_NAME

deploy:
  stage: deploy
  tags: ["shell"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Setup SSH"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
    - echo "Deploy to server"
    - scp $APP_NAME $DEPLOY_USER@$DEPLOY_HOST:$APP_DIR/$APP_NAME.new
    - |
      ssh $DEPLOY_USER@$DEPLOY_HOST "
        export ENV_PATH=$ENV_PATH
        sudo install -o root -g root -m 755 \
          $APP_DIR/$APP_NAME.new $APP_DIR/$APP_NAME
        sudo systemctl restart $SERVICE_NAME
      "